name: Tortola Boatel
favicon: null
layout_spectrum: 0.51019
typography_spectrum: 0.24537
title: A cabin away from home
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1e8f7'
    - '#0172ca'
    - '#01b4e4'
    - '#806d73'
    - '#493541'
  brandStrength: 0.8838494173251092
  lightness: 0.44484013225883245
  saturation: 0.75
  rhythmicContrast: 0.6785771881695837
purpose: []
