name: Tortola Boatel
favicon: null
layout_spectrum: 0.7671771524474025
typography_spectrum: 0.46926299296319485
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8838494173251092
  lightness: 0.44484013225883245
  saturation: 0.7982146341819316
  rhythmicContrast: 0.6785771881695837
purpose: []
